name: Run NeoLoad CLI Load Test

on:
  workflow_dispatch:
    inputs:
      api_url:
        required: true
        description: 'NeoLoad Web API URL'
        default: 'https://neoload-api.saas.neotys.com/'
      token:
        required: true
        description: 'NeoLoad Web API Token'
      zone_id:
        required: true
        description: 'NeoLoad Zone ID'
      project_name:
        required: true
        description: 'NeoLoad Web Project Name'
        default: 'Demo1'

jobs:
  run-neoload-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install NeoLoad CLI
        run: pip install neoload

      - name: Login to NeoLoad Web
        run: |
          neoload login --url "${{ github.event.inputs.api_url }}" ${{ github.event.inputs.token }}

      - name: Upload Project to NeoLoad Web
        run: |
          neoload project --path Demo1.zip upload --name "${{ github.event.inputs.project_name }}"

      - name: Run Test
        run: |
          neoload run --project "${{ github.event.inputs.project_name }}" \
                      --scenario "Default" \
                      --zone "${{ github.event.inputs.zone_id }}" \
                      --name "GitHub CLI Test $(date +'%Y-%m-%d_%H-%M-%S')"

      - name: Logout from NeoLoad
        run: neoload logout
