name: Run NeoLoad Test

on:
  workflow_dispatch:

jobs:
  neoload-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get Project List from NeoLoad Web
        run: |
          curl -X GET "https://neoload.saas.neotys.com/v3/projects" \
          -H "Authorization: ApiAccessToken ${{ secrets.NELOAD_WEB_TOKEN }}"
          
