name: Run NeoLoad Test

on:
  workflow_dispatch:

jobs:
  run-neoload:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download NeoLoad CLI
        run: |
          Invoke-WebRequest -Uri https://github.com/Neotys-Labs/neoload-cli/releases/download/2.11.0/neoload-cli-2.11.0.zip -OutFile neoload-cli.zip
          Expand-Archive neoload-cli.zip -DestinationPath neoload-cli
          echo "${{ github.workspace }}\neoload-cli" >> $env:GITHUB_PATH

      - name: Run NeoLoad Test
        run: |
          neoload run \
            --project-path ./Demo1.nlp \
            --scenario "Scenario" \
            --zone "defaultzone" \
            --test-result-name "GitHub_Action_Test"

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: loadTestResults
          path: results/
