name: Run NeoLoad Test

on:
  workflow_dispatch: # Trigger manually through GitHub UI

jobs:
  run-neoload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Check out the repository code

      - name: Set up Java
        uses: actions/setup-java@v3 # Set up Java environment (version 17)
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run NeoLoad CLI via Docker
        run: |
          docker pull neoload/neoload-cli:latest # Ensure the image is pulled first
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            neoload/neoload-cli:latest run \
            --project /workspace/Demo1.nlp \
            --scenario "MyScenario" \
            --nlweb-token ${{ secrets.NELOAD_WEB_TOKEN }} \
            --report-file /workspace/loadTest/neoload-report.html

      - name: Upload NeoLoad Results
        uses: actions/upload-artifact@v4 # Upload the NeoLoad results as an artifact
        with:
          name: NeoLoad_Report
          path: loadTest/
