name: NeoLoad YAML Project Run

on:
  workflow_dispatch:
    inputs:
      api_url:
        required: true
        default: 'https://neoload-api.saas.neotys.com/'
      token:
        required: true
        description: 'NeoLoad Web Token'
      zone_id:
        required: true
        description: 'Zone ID to run the test'

jobs:
  run-neoload-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install NeoLoad CLI
        run: pip3 install neoload

      - name: Login to NeoLoad Web
        run: neoload login --url ${{ github.event.inputs.api_url }} ${{ github.event.inputs.token }}

      - name: Run NeoLoad YAML Test
        run: neoload run --project simpledemo.yml --scenario simpledemo --zone-id ${{ github.event.inputs.zone_id }}
