name: NeoLoad Github Action Test
on:
  workflow_dispatch:
    inputs:
      api_url:
        required: true
        description: 'NeoLoad Web Api Url'
        default: 'https://neoload-api.saas.neotys.com/'
      token:
        required: true
        description: 'NeoLoad Web Token'
        default: 'specify_token_or_get_it_from_credentials'
      zone_id:
        required: true
        description: 'Zone identifier'
        default: 'defaultzone'

jobs:
  neoload_cli_demo:
    name: NeoLoad CLI demo github action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local code
        uses: actions/checkout@v4

      - name: "Install NeoLoad CLI"
        run: pip3 install -U neoload
        
      - name: Get workspace list via API
        run: >
          curl -s -X GET "${{ github.event.inputs.api_url }}v3/workspaces" 
          -H "Authorization: ApiAccessToken ${{ github.event.inputs.token }}"
