name: NeoLoad GitHub Action Test

on:
  workflow_dispatch:
    inputs:
      api_url:
        required: true
        description: 'NeoLoad Web API URL'
        default: 'https://neoload-api.saas.neotys.com/'
      token:
        required: true
        description: 'NeoLoad Web API Token'
        default: 'paste_your_token_here'
      zone_id:
        required: true
        description: 'NeoLoad Zone ID'
        default: 'defaultzone'

jobs:
  neoload_cli_demo:
    name: NeoLoad CLI Demo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install NeoLoad CLI
        run: pip3 install -U neoload

      - name: Login to NeoLoad Web
        run: |
           neoload login --url ${{ github.event.inputs.api_url }} ${{ github.event.inputs.token }}
      
      - name: Upload NeoLoad Project (from zipped file in repo)
        run: |
           neoload project --path Demo1.zip upload


      # OPTIONAL: Run NeoLoad Test
      # Make sure to replace "MyScenario" with your actual scenario name
      - name: Run NeoLoad Test (Optional)
        run: |
          neoload run \
            --scenario "scenario1" \
            --zone "${{ github.event.inputs.zone_id }}" \
            --name "GitHub Run $(date +%Y%m%d%H%M%S)"
