name: NeoLoad Github Action Test

on:
  workflow_dispatch:
    inputs:
      api_url:
        required: true
        description: 'NeoLoad Web Api Url'
        default: 'https://neoload-api.saas.neotys.com/'
      token:
        required: true
        description: 'NeoLoad Web Token (leave blank to use GitHub secret)'
        default: ''
      zone_id:
        required: true
        description: 'Zone identifier'
        default: 'defaultzone'

jobs:
  neoload_cli_demo:
    name: NeoLoad CLI demo github action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local code
        uses: actions/checkout@v4

      - name: "Install NeoLoad CLI"
        run: pip3 install -U neoload

      - name: "Get NeoLoad project"
        run: >
          rm -f *.nlp;
          wget https://raw.githubusercontent.com/Sreyajit-Mondal/Neoload_Loadtest/main/Demo1.nlp

      - name: "Prepare NeoLoad test"
        env:
          NEOLOAD_TOKEN: ${{ github.event.inputs.token != '' && github.event.inputs.token || secrets.NEOLOAD_WEB_TOKEN }}
        run: >
          neoload login --url ${{ github.event.inputs.api_url }} --token $NEOLOAD_TOKEN &&
          neoload test-settings --zone ${{ github.event.inputs.zone_id }} --scenario 'scenario1' createorpatch "My Github Test With CLI" &&
          neoload project --path Demo1.nlp upload

      - name: "NeoLoad run test"
        run: >
          neoload run 
          --external-url $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID 
          --external-url-label "Github Action Run $GITHUB_RUN_NUMBER" 
          --name "Github pipeline performance regression test - Github build #$GITHUB_RUN_NUMBER" 
          --description "Example of CI performance regression job started from Github." 
          --return-0

      - name: "Generate Test Report"
        id: report
        if: ${{ always() }}
        run: neoload test-results junitsla

      - name: "Publish Test Report"
        if: steps.report.outcome == 'success'
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: junit-sla.xml
          fail_on_test_failures: true
