name: Run NeoLoad Test

on:
  workflow_dispatch:

jobs:
  run-neoload:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NeoLoad CLI
        run: |
          choco install neoload-cli -y

      - name: Run NeoLoad Test
        run: |
          neoload run \
            --project-path ./Demo1.nlp \
            --scenario "Scenario" \
            --zone "defaultzone" \
            --test-result-name "GitHub_Action_Test"

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: loadTestResults
          path: results/
