name: Run NeoLoad Test

on:
  workflow_dispatch:

jobs:
  run-neoload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run NeoLoad CLI
        uses: neotys/run-cli@v1
        with:
          project: 'Demo1.nlp'
          scenario: 'MyScenario'
          token: ${{ secrets.NEOLAOD_WEB_TOKEN }}

      - name: Upload NeoLoad Results
        uses: actions/upload-artifact@v4
        with:
          name: NeoLoad_Report
          path: ${{ github.workspace }}/loadTest
