name: Run NeoLoad Test

on:
  workflow_dispatch:

jobs:
  run-neoload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install NeoLoad CLI
        run: pip install neoload

      - name: Run NeoLoad Test
        env:
          NEOTOKEN: ${{ secrets.NELOAD_WEB_TOKEN }}
        run: |
          echo "🔐 Debug: Token starts with: ${NEOTOKEN:0:4}"
          if [ -z "$NEOTOKEN" ]; then
            echo "❌ NEOTOKEN is empty! Make sure the GitHub secret is set correctly."
            exit 1
          fi

          echo "✅ Logging in to NeoLoad..."
          neoload login "$NEOTOKEN"

          echo "🚀 Running NeoLoad test..."
          neoload run \
            --project Demo1.nlp \
            --scenario "MyScenario" \
            --report-file loadTest/neoload-report.html

      - name: Upload NeoLoad Results
        uses: actions/upload-artifact@v4
        with:
          name: NeoLoad_Report
          path: loadTest/
